apiVersion: v1
kind: Service
metadata:
  name: my-internal-service
spec:
  selector:
    app: python-hello-world
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello-world
spec:
  selector:
    matchLabels:
      app: python-hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: python-hello-world
    spec:
      containers:
        - name: python-hello-world
          image: berezovsky8/python:latest
